<a href="https://colab.research.google.com/github/MiguelPartosa/Thesis-FOS-BinaryClass-WSD/blob/main/Thesis_Implementation_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preload Models

## CEB POS Tagger -- POS Tagging

### Setup

In [1]:
!git clone https://github.com/MiguelPartosa/Thesis-FOS-BinaryClass-WSD.git
%cd Thesis-FOS-BinaryClass-WSD/
%cd Cebuano_POS_Tagger/
!pip install -r requirements.txt
import nltk
nltk.download('punkt_tab')

c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\Thesis-FOS-BinaryClass-WSD
c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\Thesis-FOS-BinaryClass-WSD\Cebuano_POS_Tagger

fatal: destination path 'Thesis-FOS-BinaryClass-WSD' already exists and is not an empty directory.
c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\.venv\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

Collecting backports-abc==0.5 (from -r requirements.txt (line 1))
  Using cached backports_abc-0.5-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting backports.shutil-get-terminal-size==1.0.0 (from -r requirements.txt (line 2))
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting backports.shutil-which==3.5.1 (from -r requirements.txt (line 3))
  Using cached backports.shutil_which-3.5.1-py2.py3-none-any.whl.metadata (769 bytes)
Collecting bleach==2.1.3 (from -r requirements.txt (line 4))
  Using cached bleach-2.1.3-py2.py3-none-any.whl.metadata (15 kB)
Collecting colorama==0.3.9 (from -r requirements.txt (line 5))
  Using cached colorama-0.3.9-py2.py3-none-any.whl.metadata (13 kB)
Collecting configparser==3.5.0 (from -r requirements.txt (line 6))
  Using cached configparser-3.5.0.tar.gz (39 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting decorator==4.3.0 (from -r requirements.txt (line 7))
  Using cached decorator-4.3.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting entrypoints==0.2.3 (from -r requirements.txt (line 8))
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl.metadata (382 bytes)
Collecting enum34==1.1.6 (from -r requirements.txt (line 9))
  Using cached enum34-1.1.6-py3-none-any.whl.metadata (1.7 kB)

ERROR: Ignored the following yanked versions: 3.1.0, 3.1.1
ERROR: Ignored the following versions that require a different python version: 3.1.1.post1 Requires-Python >=2.6, <3; 3.2.0 Requires-Python >=2.6, <3; 3.3.0 Requires-Python >=2.6, <3; 3.4.0 Requires-Python >=2.6, <3
ERROR: Could not find a version that satisfies the requirement futures==3.2.0 (from versions: 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
ERROR: No matching distribution found for futures==3.2.0
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Miguel\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

### Test

In [2]:
from cebpostagger.tagger import tag_sentence

print(tag_sentence('Ang bata naligo sa sapa.'))
print(tag_sentence('Ganahan kog prutas.'))

[(b'Ang', 'DET'), (b'bata', 'NOUN'), (b'naligo', 'VERB'), (b'sa', 'PART'), (b'sapa', 'NOUN'), (b'.', 'SYM')]
[(b'Ganahan', 'VERB'), (b'kog', 'PRON'), (b'prutas', 'NOUN'), (b'.', 'SYM')]

## NLLB -- Translataion

In [3]:
from transformers import pipeline

pipe = pipeline("translation", model="facebook/nllb-200-distilled-600M")

c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
text_to_translate = "I love chicken!"

translated_text = pipe(
    text_to_translate, src_lang="eng_Latn", tgt_lang="ceb_Latn")
translated_text

[{'translation_text': 'Ganahan ko sa manok!'}]

## Sentence Transformer -- Sentence Embeddings

In [5]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/LaBSE')

# Dataset Preparation

## Importing Dataset

In [6]:
import pandas as pd

# @param ["Root Folder", "Cebuano_POS_Tagger"]
dataset_location = "Root Folder"
dataset_file_name = "Raw_Dataset"  # @param {type: "string"}

# For ease of use, we allow importing the dataset into the root folder
dataset_file_name = "../../" + \
    dataset_file_name if dataset_location == "Root Folder" else dataset_file_name

df = pd.read_excel(dataset_file_name + ".xlsx", sheet_name="Cebuano_Examples")
df.head()

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,a mere mortal; an ordinary person; someone wit...,No,Wiktionary,ChatGPT 4o
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,used to dismiss people's opinion on one's luck...,No,Wiktionary,ChatGPT 4o

### Tag Verbs and Filter

In [7]:
def ReturnTags(text: str) -> str:
    try:
        return tag_sentence(text)
    except Exception as e:
        print(f"{e}\n\n Input:{text}")
        return None

In [8]:
df_filtered = df.copy()
df_filtered['POS Tags'] = df_filtered.iloc[:, 0].apply(lambda x: ReturnTags(x))
df_filtered

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example,POS Tags
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o,"[(b'alsa', VERB), (b'og', CONJ), (b'balay', NO..."
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o,"[(b'anak', NOUN), (b'sa', PART), (b'bugoon', N..."
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,a mere mortal; an ordinary person; someone wit...,No,Wiktionary,ChatGPT 4o,"[(b'anak', NOUN), (b'sa', PART), (b'pobreng', ..."
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'baka', NOUN), (b'nisulod', ..."
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,used to dismiss people's opinion on one's luck...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'demalas', ADJ), (b'naa', AD..."
...,...,...,...,...,...,...,...,...,...
317,murag iring ug iro,"""Si Juan ug Pedro murag iring ug iro, sige lan...",simile,Bisaya,(simile) cannot get along with each other,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'iring', NOUN), (b'ug', CO..."
318,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(simile, idiomatic) nouveau riche; new money; ...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'langaw', NOUN), (b'nga', ..."
319,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,used to describe someone who cries bawlingly o...,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namatyag', VERB), (b'irin..."
320,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...",simile,Bisaya,"(simile, idiomatic) someone who leaves unexpec...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namiya', OTH), (b'og', CO..."
321,tin-aw pa sa sabaw sa butong,"""Ang iyang pangutana tin-aw pa sa sabaw sa but...",simile,Bisaya,"(idiomatic, simile) clear as day, clear as cry...",No,Wiktionary,ChatGPT 4o,"[(b'tin-aw', ADJ), (b'pa', ADV), (b'sa', PART)..."

#### Dataset- Export Dataset with POS Tags
- End of the first phase of preprocessing 
- Unnecessary columns are dropped and columns with no meaning will be filtered out

In [9]:
# df_filtered.iloc[:,]
df_preprocessed = df_filtered[['Fos','Examples','Meaning_en','POS Tags']]
print("Shape before dropping NA columns: ", df_preprocessed.dropna().shape,"\nShape after dropping: ", df_preprocessed.shape)
# Dropping 12 columns
df_preprocessed.dropna(inplace=True)
df_preprocessed.reset_index(inplace=True, drop=True)

Shape before dropping NA columns:  (310, 4)
Shape after dropping:  (322, 4)

C:\Users\Miguel\AppData\Local\Temp\ipykernel_9744\3604860608.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preprocessed.dropna(inplace=True)

In [10]:
df_preprocessed.to_excel(
    '../../Dataset/Tagged_POS.xlsx', sheet_name="Tagged POS", index=False)

After Manual verification, `df_filtered` is reassigned to the manually verified dataset with the proper tags

In [ ]:
#TODO

In [19]:
def ContainsVerbs(item: list) -> bool:
    return 1 if any('VERB' in x for x in item) else 0

In [20]:
df_filtered['Contains Verbs'] = df_filtered.iloc[:, 8].apply(
    lambda x: ContainsVerbs(x))
df_filtered

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example,POS Tags,Contains Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o,"[(b'alsa', VERB), (b'og', CONJ), (b'balay', NO...",1
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o,"[(b'anak', NOUN), (b'sa', PART), (b'bugoon', N...",0
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,a mere mortal; an ordinary person; someone wit...,No,Wiktionary,ChatGPT 4o,"[(b'anak', NOUN), (b'sa', PART), (b'pobreng', ...",0
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'baka', NOUN), (b'nisulod', ...",1
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,used to dismiss people's opinion on one's luck...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'demalas', ADJ), (b'naa', AD...",0
...,...,...,...,...,...,...,...,...,...,...
317,murag iring ug iro,"""Si Juan ug Pedro murag iring ug iro, sige lan...",simile,Bisaya,(simile) cannot get along with each other,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'iring', NOUN), (b'ug', CO...",0
318,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(simile, idiomatic) nouveau riche; new money; ...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'langaw', NOUN), (b'nga', ...",1
319,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,used to describe someone who cries bawlingly o...,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namatyag', VERB), (b'irin...",1
320,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...",simile,Bisaya,"(simile, idiomatic) someone who leaves unexpec...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namiya', OTH), (b'og', CO...",0
321,tin-aw pa sa sabaw sa butong,"""Ang iyang pangutana tin-aw pa sa sabaw sa but...",simile,Bisaya,"(idiomatic, simile) clear as day, clear as cry...",No,Wiktionary,ChatGPT 4o,"[(b'tin-aw', ADJ), (b'pa', ADV), (b'sa', PART)...",0

### Verification
- The dataset will be reimported after manual verification

### Filtering Non-Verbs
- Verification must be done before filtering out tagged verbs

In [11]:
# df_verbs_filtered = df_filtered[df_filtered.iloc[:, 9] == True].reset_index(
#     drop=True)
# df_verbs_filtered

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example,POS Tags,Contains Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o,"[(b'alsa', VERB), (b'og', CONJ), (b'balay', NO...",True
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'baka', NOUN), (b'nisulod', ...",True
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",catchphrases,Bisaya,used to tell someone not to criticize or hate ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'masuya', VERB), (b'madeads'...",True
3,ayaw pagbuot kay lain-lain ta og lubot,"Ayaw pagbuot kay lain-lain ta og lubot, respet...",catchphrases,Bisaya,don't tell me what to do,No,Wiktionary,ChatGPT 4o,"[(b'ayaw', VERB), (b'pagbuot', NOUN), (b'kay',...",True
4,"ayaw pagbuot, lain-lain tag lubot","Ayaw pagbuot, lain-lain tag lubot, tanan kita ...",catchphrases,Bisaya,don't tell me what to do,No,Wiktionary,ChatGPT 4o,"[(b'ayaw', VERB), (b'pagbuot', NOUN), (b',', S...",True
...,...,...,...,...,...,...,...,...,...,...
166,untwa,"""Untwa imong mga plano, walay klaro.""; ""Si Ana...",sarcastic_terms,Bisaya,(sarcastic) what,No,Wiktionary,ChatGPT 4o,"[(b'untwa', VERB)]",True
167,mura og halas nga nagluno,"""Ang iyang mga sinina nagkatag mura og halas n...",simile,Bisaya,"(idiomatic, simile) someone who leaves their d...",No,Wiktionary,ChatGPT 4o,"[(b'mura', ADJ), (b'og', CONJ), (b'halas', NOU...",True
168,murag gitilapan og iring,"""Ang iyang sapatos murag gitilapan og iring, l...",simile,Bisaya,(simile) spotless; spick-and-span,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'gitilapan', VERB), (b'og'...",True
169,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(simile, idiomatic) nouveau riche; new money; ...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'langaw', NOUN), (b'nga', ...",True
170,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,used to describe someone who cries bawlingly o...,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namatyag', VERB), (b'irin...",True

### Word Sense Cleaning

- Checking Null values and removing them

In [ ]:
print("NA Columns in Meaning_en:", df_verbs_filtered.iloc[:, 4].isna().sum())

df_verbs_filtered.dropna(inplace=True)
df_verbs_filtered.reset_index(drop=True, inplace=True)
print("Dropped:")
df_verbs_filtered

NA Columns in Meaning_en: 8
Dropped:

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example,POS Tags,Contains Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o,"[(b'alsa', VERB), (b'og', CONJ), (b'balay', NO...",True
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'baka', NOUN), (b'nisulod', ...",True
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",catchphrases,Bisaya,used to tell someone not to criticize or hate ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'masuya', VERB), (b'madeads'...",True
3,ayaw pagbuot kay lain-lain ta og lubot,"Ayaw pagbuot kay lain-lain ta og lubot, respet...",catchphrases,Bisaya,don't tell me what to do,No,Wiktionary,ChatGPT 4o,"[(b'ayaw', VERB), (b'pagbuot', NOUN), (b'kay',...",True
4,"ayaw pagbuot, lain-lain tag lubot","Ayaw pagbuot, lain-lain tag lubot, tanan kita ...",catchphrases,Bisaya,don't tell me what to do,No,Wiktionary,ChatGPT 4o,"[(b'ayaw', VERB), (b'pagbuot', NOUN), (b',', S...",True
...,...,...,...,...,...,...,...,...,...,...
158,untwa,"""Untwa imong mga plano, walay klaro.""; ""Si Ana...",sarcastic_terms,Bisaya,(sarcastic) what,No,Wiktionary,ChatGPT 4o,"[(b'untwa', VERB)]",True
159,mura og halas nga nagluno,"""Ang iyang mga sinina nagkatag mura og halas n...",simile,Bisaya,"(idiomatic, simile) someone who leaves their d...",No,Wiktionary,ChatGPT 4o,"[(b'mura', ADJ), (b'og', CONJ), (b'halas', NOU...",True
160,murag gitilapan og iring,"""Ang iyang sapatos murag gitilapan og iring, l...",simile,Bisaya,(simile) spotless; spick-and-span,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'gitilapan', VERB), (b'og'...",True
161,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(simile, idiomatic) nouveau riche; new money; ...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'langaw', NOUN), (b'nga', ...",True
162,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,used to describe someone who cries bawlingly o...,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namatyag', VERB), (b'irin...",True

In [14]:
%ls

 Volume in drive C is OS
 Volume Serial Number is C05C-D5A4

 Directory of c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\Thesis-FOS-BinaryClass-WSD\Cebuano_POS_Tagger

01/17/2025  12:17 PM    <DIR>          .
01/17/2025  12:17 PM    <DIR>          ..
01/17/2025  12:17 PM    <DIR>          build
01/17/2025  12:18 PM    <DIR>          cebpostagger
01/17/2025  12:17 PM    <DIR>          cebpostagger.egg-info
01/17/2025  12:17 PM    <DIR>          dist
01/17/2025  12:17 PM    <DIR>          eval
01/17/2025  12:17 PM             7,816 LICENSE
01/17/2025  12:17 PM    <DIR>          packages
01/17/2025  12:17 PM             1,067 requirements.txt
01/17/2025  12:17 PM                40 setup.cfg
01/17/2025  12:17 PM               562 setup.py
01/17/2025  12:17 PM               300 test_tagger.py
               5 File(s)          9,785 bytes
               8 Dir(s)  90,196,717,568 bytes free

In [18]:
df_verbs_filtered.to_excel(
    '../../Cleaned_Word_sense.xlsx', sheet_name="Cleaned Word Sense", index=False)

### Translate English Wordsense into Cebuano

In [ ]:
!pip install tqdm
from tqdm import tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

In [ ]:
example = df.iloc[:2]
example

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o

Translator example from nllb

In [ ]:
def TranslateCebuano(text: str) -> str:
    try:
        translated_text = pipe(text, src_lang="eng_Latn", tgt_lang="ceb_Latn")
        return translated_text[0]['translation_text']
    except Exception as e:
        print(f"{e}\n\n Input:{text}")
        return ""

In [ ]:
print("Original Example: ", example.iloc[:, 4][0], "\n\nTranslated:", TranslateCebuano(
    example.iloc[:, 4][0]))

Original Example:  said to self or someone when the meal includes mung beans

Translated: gisulti sa kaugalingon o sa uban kon ang pagkaon naglakip sa mung beans

In [ ]:
df_translated = df.copy()
df_translated.iloc[:, 4] = df_translated.iloc[:, 4].apply(
    lambda x: TranslateCebuano(x))
df_translated

Your input_length: 819 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan

Your input_length: 234 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
Your input_length: 453 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
Token indices sequence length is longer than the specified maximum sequence length for this model (1554 > 1024). Running this sequence through the model will result in indexing errors
Your input_length: 1554 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan

Your input_length: 314 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan

Your input_length: 377 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,gisulti sa kaugalingon o uban kon ang pagkaon ...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(masulob-on nga mapahitas-on) gigamit sa pagta...,No,Wiktionary,ChatGPT 4o
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,usa ka mortal lamang; usa ka ordinaryo nga taw...,No,Wiktionary,ChatGPT 4o
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,gigamit sa pagsulti sa usa nga siya usa ka bak...,No,Wiktionary,ChatGPT 4o
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,gigamit sa paglabay sa opinyon sa mga tawo bah...,No,Wiktionary,ChatGPT 4o
...,...,...,...,...,...,...,...,...
317,murag iring ug iro,"""Si Juan ug Pedro murag iring ug iro, sige lan...",simile,Bisaya,(simile) dili makab-ot sa usag usa,No,Wiktionary,ChatGPT 4o
318,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(similar, idiomatic) nouveau rich; bag-ong sal...",No,Wiktionary,ChatGPT 4o
319,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,gigamit sa paghulagway sa usa ka tawo nga nagt...,No,Wiktionary,ChatGPT 4o
320,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...",simile,Bisaya,"(same, idiomatic) usa ka tawo nga mibiya sa di...",No,Wiktionary,ChatGPT 4o
321,tin-aw pa sa sabaw sa butong,"""Ang iyang pangutana tin-aw pa sa sabaw sa but...",simile,Bisaya,"(idiomatic, simile) limpyo sama sa adlaw, limp...",No,Wiktionary,ChatGPT 4o

# Dataset Transformation

## TODO for 50%

- [ ] Import dataset with pandas
- [ ] Run CEBPOS tags on column 2 and filter
- [ ] Transform per row example in column 28 into multiple rows
- [ ] Use gpt to generate literal examples and find literal example from seperate dataset
- [ ] Show innacurate/hallucinated generated from gpt examples and remove from rows

## Maybe included ?

- [ ] Train Test split